# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Decrypt Firebase Secret
        run: |
          chmod +x decrypt_firebase_secret.sh
          ./decrypt_firebase_secret.sh
        env:
          FIREBASE_SECRET_PASSPHRASE: ${{ secrets.FIREBASE_SECRET_PASSPHRASE }}
      # Setup Heroku
      - name: Setup Heroku CLI
        run: sudo snap install --classic heroku
      # Setup Heroku Git
      - name: Setup Heroku GIT
        run: |
          rm -rf .git
          git init
          git config --global user.name "Eugene"
          git config --global user.email ${{ secrets.MY_EMAIL }}
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
          sudo printf "${{ secrets.NETRC }}" >> ~/.netrc
          git add .
          git commit -m "ROCK YOU"
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
          
      # Set Default ENV
      - name: Set Default ENV
        run: heroku config:set $(cat .env.example | sed '/^$/d; /#[[:print:]]*$/d')
      # Update Production ENV
      - name: Update Production ENV
        run: |
          heroku config:add APP_ENV=production
          heroku config:add APP_KEY=${{ secrets.APP_KEY }}
          heroku config:add APP_DEBUG=false
          heroku config:add APP_URL=${{ secrets.APP_URL }}
          heroku config:add DB_CONNECTION=pgsql
          heroku config:add DB_HOST=${{ secrets.DB_HOST }}
          heroku config:add DB_PORT=${{ secrets.DB_PORT }}
          heroku config:add DB_DATABASE=${{ secrets.DB_DATABASE }}
          heroku config:add DB_USERNAME=${{ secrets.DB_USERNAME }}
          heroku config:add DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          heroku config:add OAUTH2_DEFAULT_PASSWORD=${{ secrets.APP_KEY }}
          heroku config:add GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          heroku config:add GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          heroku config:add FIREBASE_CREDENTIALS=firebase_secret.json
          heroku config:add GOOGLE_OAUTH_REDIRECT=${{ secrets.APP_URL }}/api/v1/android/auth/oauth2/google/authorize
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
      # Push New Changes
      - name: Push new changes to heroku
        run: |
          git push -f heroku master
