# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup Heroku
      - name: Setup Heroku CLI
        run: sudo snap install --classic heroku
      # Login Heroku
      - name: Login Heroku
        run: HEROKU_API_KEY='${{ secrets.HEROKU_TOKEN }}'
      # Setup Heroku Git
      - name: Setup Heroku GIT
        run: heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
      # Set Default ENV
      - name: Set Default ENV
        run: heroku config:set $(cat .env.example | sed '/^$/d; /#[[:print:]]*$/d')
      # Update Production ENV
      - name: Update Production ENV
        run: |
          heroku config:add APP_ENV=production
          heroku config:add APP_KEY=${{ secrets.APP_KEY }}
          heroku config:add APP_DEBUG=false
          heroku config:add APP_URL=${{ secrets.APP_URL }}
          heroku config:add DB_CONNECTION=pgsql
          heroku config:add DB_HOST=${{ secrets.DB_HOST }}
          heroku config:add DB_PORT=${{ secrets.DB_PORT }}
          heroku config:add DB_DATABASE=${{ secrets.DB_DATABASE }}
          heroku config:add DB_USERNAME=${{ secrets.DB_USERNAME }}
          heroku config:add DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      # Push New Changes
      - name: Push new changes to heroku
        run: git push -f heroku master
